/**
 * Error codes used in error and contentError events.
 */

export enum ErrorCode {
  // Video/adapter errors
  VIDEO_LOAD_FAILED = "VIDEO_LOAD_FAILED",
  ADAPTER_ERROR = "ADAPTER_ERROR",
  ADAPTER_UNSUPPORTED = "ADAPTER_UNSUPPORTED",

  // Content type errors
  CONTENT_TYPE_NOT_FOUND = "CONTENT_TYPE_NOT_FOUND",
  CONTENT_TYPE_VERSION_MISMATCH = "CONTENT_TYPE_VERSION_MISMATCH",
  CONTENT_TYPE_MIGRATION_FAILED = "CONTENT_TYPE_MIGRATION_FAILED",
  CONTENT_TYPE_RENDER_ERROR = "CONTENT_TYPE_RENDER_ERROR",

  // Validation errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  OVERLAP_VALIDATION_ERROR = "OVERLAP_VALIDATION_ERROR",

  // Deserialization errors
  DESERIALIZATION_ERROR = "DESERIALIZATION_ERROR",

  // Preload errors
  PRELOAD_ERROR = "PRELOAD_ERROR",
}

export enum ContentErrorCode {
  RENDER_FAILED = "RENDER_FAILED",
  VERSION_MISMATCH = "VERSION_MISMATCH",
  MIGRATION_FAILED = "MIGRATION_FAILED",
  UNKNOWN_CONTENT_TYPE = "UNKNOWN_CONTENT_TYPE",
}
